### ISSUE TITLE
missing UTF8 encoding in Formularz.java

### ISSUE THREAD

**Issue by adamkowalewski** [openpkw/PocKalkulatorWyborczyHtml#1]
Proszę sprawdźcie wasze ustawienia w Eclipse. 
Klasa `Formularz.java` linia 21 
```java
} catch (Exception ex) {
	return "B��d: "+numberStr;
}
```
Tak wygląda kod w edytorze NetBeans pod Ubuntu 12.4 x64 LTS.

**Comment by SebastianCelejewski** [comment]
Poprawiłem w kodzie. W readme dopisałem porady dla Eclipsowców.
